### ISSUE TITLE
Cannot get the token by following readme

### ISSUE THREAD

**Issue by ZhiLiGod** [docusign/eg-01-java-jwt#4]
Hi there,

I followed the readme and still cannot get the token. See below
![image](https://user-images.githubusercontent.com/29784334/60202376-58683a80-9842-11e9-9c92-265c56fec9ab.png)

I changed all info in .property file and also added \n\ on each line of the private key.

Regards,
Zhi

**Comment by ZhiLiGod** [comment]
Tried with two sandboxes and both doesn't work. I am pretty sure that I used integrator key and username ID, also the private key. Still cannot get the token.

**Comment by LarryKlugerDS** [comment]
I'm sorry you're having this problem. I suggest the fastest place to get help is our StackOverflow channel -- use tag `docusignapi`

You'll also want to include the relevant parts of your source. Change the middle of the integration key and private key to XXXXX so you're not disclosing that information publicly.

**Comment by ronakcshah** [comment]
Any update or way to fix the issue? 

I'm running into the same thing, and, have this open on [stackoverflow](https://stackoverflow.com/questions/57208195/error-when-generating-docusign-jwt-token-in-java)

**Comment by ZhiLiGod** [comment]
Hi, look at here, I have got it fixed. https://stackoverflow.com/questions/56792293/having-issue-when-getting-jwt-token-by-using-docusign-api
